name: Code Watcher - Error Checker

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Launch checkout v2
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check errors (via SuperLinter v3)
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}